Imports DevExpress.XtraReports.UI
Imports DevExpress.XtraReports.UI.CrossTab
Imports System
Imports System.Windows.Forms
' ...

Namespace RepPGVertHeadersHeight
	Partial Public Class Form1
		Inherits Form

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			' Fill a SqlDataSource asynchronously
			sqlDataSource1.Fill()
		End Sub

		Private Sub button1_Click(ByVal sender As Object, ByVal e As EventArgs) Handles button1.Click
			'Apply Best Fit to "CategoryName" column
			pivotGridControl1.Fields("CategoryName").BestFit()
		End Sub

		Private Sub button2_Click(ByVal sender As Object, ByVal e As EventArgs) Handles button2.Click
			Using report As XtraReport = New XtraReport1()
			Using tool As New ReportPrintTool(report)

				Dim crossTab As XRCrossTab = TryCast(report.FindControl("xrCrossTab1", False), XRCrossTab)

				'Apply Best Fit to "CategoryName" column
				TryCast(crossTab.Cells("ctcCategoryName"), XRCrossTabCell).ColumnAutoWidthMode = DevExpress.XtraReports.UI.AutoSizeMode.ShrinkAndGrow


				tool.ShowPreviewDialog()
			End Using
			End Using
		End Sub
	End Class
End Namespace